CATEGORIES_MAP = {
    "Economic": "Ekonomiczna",
    "Fantasy": "Fantasy",
    "Card Game": "Karciana",
    "Science Fiction": "Sci-Fi",
    "Fighting": "Bijatyka",
    "Adventure": "Przygodowa",
    "Medieval": "Średniowieczna",
    "Miniatures": "Miniaturkowa",
    "Exploration": "Eksploracyjna",
    "City Building": "Budowanie miasta",
    "Wargame": "Wojenna",
    "Dice": "Kościana",
    "Civilization": "Cywilizacyjna",
    "Territory Building": "Terytorialna",
    "Space Exploration": "Ekslporacja kosmosu",
    "Industry / Manufacturing": "Przemysłowa",
    "Deduction": "Dedukcyjna",
    "Animals": "O zwierzętach",
    "Ancient": "Starożytna",
    "Mythology": "Mitologiczna",
    "Farming": "Rolnicza",
    "Horror": "Horror",
    "Political": "Polityczna",
    "Renaissance": "Renesansowa",
    "Nautical": "Żeglarska",
    "Puzzle": "Łamigłówkowa",
    "Travel": "Podróżnicza",
    "Party Game": "Imprezowa",
    "Murder/Mystery": "Kryminalna",
    "Video Game Theme": "Na podstawie gry wideo",
    "Mature / Adult": "Dla dorosłych",
    "Zombies": "Zombie",
    "Prehistoric": "Prehistoryczna",
    "World War II": "O Drugiej Wojnie Światowej",
    "Humor": "Humorystyczna",
}

MECHANICS_MAP = {
    "Hand Management": "Zarządzanie ręką",
    "Variable Player Powers": "Zmienne moce gracza",
    "Dice Rolling": "Rzuczanie kośćmi",
    "Solo / Solitaire Game": "Tryb gry solo",
    "Open Drafting": "Otwarty dobór",
    "Set Collection": "Zbieranie zestawów",
    "Area Majority / Influence": "Wpływ na obszar gry",
    "End Game Bonuses": "Bonusy końcowe",
    "Variable Set-up": "Zmienny start gry",
    "Worker Placement": "Rozmieszczanie robotników",
    "Modular Board": "Modularna plansza",
    "Cooperative Game": "Współpraca",
    "Tile Placement": "Rozmieszczanie kafelków",
    "Deck, Bag, and Pool Building": "Budowanie ręki lub talii",
    "Action Points": "Punkty akcji",
    "Area Movement": "Poruszanie się po planszy",
    "Hexagon Grid": "Siatka heksagonalna",
    "Contracts": "Kontrakty",
    "Income": "Przychód",
    "Scenario / Mission / Campaign Game": "Scenariusze gry",
    "Simultaneous Action Selection": "Jednoczesny wybór akcji",
    "Events": "Wydarzenia",
    "Team-Based Game": "Gra zespołowa",
    "Auction/Bidding": "Licytacje",
    "Tech Trees / Tech Tracks": "Drzewko rozwoju",
    "Push Your Luck": "Losowość",
    "Role Playing": "RPG",
    "Storytelling": "Opowiadanie historii",
    "Player Elimination": "Eliminacja graczy",
    "Square Grid": "Siatka kwadratowa",
    "Simulation": "Symulacja",
    "Market": "Rynek",
    "Trading": "Handel",
    "Movement Points": "Punkty ruchu",
    "Deck Construction": "Budowanie talii",
    "Voting": "Głosowanie",
}
