# Generated by Django 4.1 on 2022-09-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polecacz', '0008_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='opinion_created',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
